main: main.cpp
	g++ -std=c++11 main.cpp -o main -lncurses

recordes: testeRecordes.cpp
	g++ -std=c++11 testeRecordes.cpp -o testeRecordes

snake: snake.cpp
	g++ -std=c++11 snake.cpp -o snake

all: run

run: main
	./main

clean:
	rm main
